### ISSUE TITLE
Uncaught TypeError: Cannot set property 'DateRange' of undefined

### ISSUE THREAD

**Issue by krsnaa** [gf3/moment-range#101] opened 2015-12-26 16:55 UTC
Install moment-range using npm, import it into .js file (import {} from 'moment-range';) and bam! you can see the error in the browser console window when rendering the page. you don't even have to use any functionality. It appears that the root parameter is undefined. a simple fix seems to just involve setting it to an empty object like so:

if (typeof root === "undefined") { root = {}; }

FWIW, here is my package.json:
 "dependencies": {
    "moment": "^2.10.6",
    "moment-range": "^2.1.0",
    "react": "^0.14.3",
    "react-dom": "^0.14.3"
  },
  "devDependencies": {
    "babel-core": "^5.8.34",
    "babel-loader": "^5.3.3",
    "webpack": "^1.12.9"
  }

**Comment by ivancho98** [comment] 2016-01-19 12:09
I had a similar problem when running my tests in Karma with webpack. Actually there is no need to import the moment-range explictly. You can just import moment js, and call moment.range(), if moment-range is in you dependencies, it should work.

**Comment by szubtsovskiy** [comment] 2016-02-19 14:01
It might depend on the operating system. I did some investigation and expressed my thoughts here: https://github.com/onefinestay/react-daterange-picker/issues/66#issuecomment-186212935

However, this hypothesis is still pending approval. I would appreciate any input.

**Comment by ivancho98** [comment] 2016-02-19 15:05
I think it is rather the way the requires are bundled. For my app I use webpack and it works smoothly, but when I want unit test (mocha and chai) and run it with Karma it throws the TypeError mentioned earlier.

**Comment by szubtsovskiy** [comment] 2016-02-19 17:16
You are right saying that it depends on the way the required are bundled. However it looks like this way depends on the operating system. I have copied the bundle generated in OS X to the Ubuntu server and my integration test passed. When I run it against a bundle generated on this Ubuntu server it fails.

It looks like an issue in Webpack rather than in moment-range though.

**Comment by moust** [comment] 2016-03-14 16:00
I noticed that it work if I modify the module definition by inverting "define" and "export" test block like following :
```javascript
if (typeof exports === 'object' && typeof module !== 'undefined') {
    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like environments that support module.exports,
    // like Node.
    module.exports = factory(require("moment"));
  } else if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module unless amdModuleId is set
    define(["moment"], function (a0) {
      return (root['DateRange'] = factory(a0));
    });
  } else {
    root['DateRange'] = factory(moment);
  }
```

Else, it's possible to manage this issue by using the webpack [imports-loader](https://github.com/webpack/imports-loader) like this :
```javascript
require("imports?define=>false!moment-range");
```

**Comment by Xplouder** [comment] 2016-05-16 18:59
Any workaround for this with **browserify**?
Seems like with `import moment from "moment-range";` my bundle reproduce the following error: 

> bundle.js:2335 Uncaught TypeError: _momentRange2.default.range is not a function

**Comment by gf3** [comment] 2016-12-08 03:21
hopefully this will be fixed in the upcoming v3 release, i've switched to a much more modern UMD generation tool. sorry for the troubles

**Comment by gf3** [comment] 2017-01-10 01:04
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions

**Closed by gf3** 2017-01-10 01:04 UTC
Labels: done-v3
